import { ProductType } from '@entities/product';

import Img from '@assets/images/mens-bracelets-leather-metal.jpg';

export const products_mock: ProductType[] = [
  {
    id: '1',
    name: 'Stainless Steel Chain',
    category: 'Chains',
    price: 299,
    images: [Img],
    description: '',
  },
  {
    id: '2',
    name: 'Black Onyx Signet Ring',
    category: 'Rings',
    price: 449,
    images: [Img],
    description: '',
  },
  {
    id: '3',
    name: 'Leather Wrap Bracelet',
    category: 'Bracelets',
    price: 179,
    images: [Img],
    description: '',
  },
  {
    id: '4',
    name: 'Gold Cuban Link Chain',
    category: 'Chains',
    price: 899,
    images: [Img],
    description: '',
  },
  {
    id: '5',
    name: 'Titanium Wedding Band',
    category: 'Rings',
    price: 349,
    images: [Img],
    description: '',
  },
  {
    id: '6',
    name: 'Silver Cuff Bracelet',
    category: 'Bracelets',
    price: 259,
    images: [Img],
    description: '',
  },
  {
    id: '7',
    name: 'Gold Signet Ring',
    category: 'Rings',
    price: 599,
    images: [Img],
    description: '',
  },
  {
    id: '8',
    name: 'Beaded Stone Bracelet',
    category: 'Bracelets',
    price: 129,
    images: [Img],
    description: '',
  },
  {
    id: '9',
    name: 'Silver Dog Tag Necklace',
    category: 'Chains',
    price: 199,
    images: [Img],
    description: '',
  },
  {
    id: '10',
    name: 'Stainless Steel Cufflinks',
    category: 'Cufflinks',
    price: 149,
    images: [Img],
    description: '',
  },
  {
    id: '11',
    name: 'Black Leather Bracelet',
    category: 'Bracelets',
    price: 89,
    images: [Img],
    description: '',
  },
  {
    id: '12',
    name: 'Platinum Band Ring',
    category: 'Rings',
    price: 799,
    images: [Img],
    description: '',
  },
];
