import { ProductType } from '@entities/product';

import Img from '@assets/images/mens-bracelets-leather-metal.jpg';

export const products_mock: ProductType[] = [
  {
    id: '1',
    name: 'Stainless Steel Chain',
    category: 'Chains',
    price: 299,
    images: [Img, Img],
    description:
      'A bold and durable stainless steel chain that combines modern aesthetics with timeless style. Perfect for everyday wear or special occasions.',
    material: '316L Stainless Steel',
    length: '24 inches',
    width: '6mm',
    features: [
      'Hypoallergenic',
      'Water resistant',
      'Tarnish resistant',
      'Secure lobster clasp',
    ],
  },
  {
    id: '2',
    name: 'Black Onyx Signet Ring',
    category: 'Rings',
    price: 449,
    images: [Img, Img],
    description:
      'An elegant signet ring featuring a polished black onyx stone set in sterling silver. A statement piece that exudes confidence and sophistication.',
    material: 'Sterling Silver, Black Onyx',
    sizes: ['8mm,', '9mm,', '10mm,', '11mm,', '12mm'],
    width: '12mm',
    features: [
      'Natural black onyx stone',
      'Hand-polished finish',
      'Comfort fit band',
      'Gift box included',
    ],
  },
  {
    id: '3',
    name: 'Leather Wrap Bracelet',
    category: 'Bracelets',
    price: 179,
    images: [Img, Img],
    description:
      'Handcrafted genuine leather bracelet with stainless steel magnetic clasp. The perfect blend of rugged and refined for the modern man.',
    material: 'Genuine Leather, Stainless Steel',
    length: 'Adjustable 7-9 inches',
    width: '8mm',
    features: [
      'Genuine Italian leather',
      'Magnetic clasp',
      'Adjustable fit',
      'Handmade craftsmanship',
    ],
  },
  {
    id: '4',
    name: 'Gold Cuban Link Chain',
    category: 'Chains',
    price: 899,
    images: [Img, Img],
    description:
      'Classic Cuban link chain crafted in 14K gold. A timeless piece that adds luxury and style to any outfit.',
    material: '14K Gold',
    length: '22 inches',
    width: '8mm',
    features: [
      '14K solid gold',
      'Heavy weight construction',
      'Secure box clasp',
      'Certificate of authenticity',
    ],
  },
  {
    id: '5',
    name: 'Titanium Wedding Band',
    category: 'Rings',
    price: 349,
    images: [Img, Img],
    description:
      'Sleek and modern titanium wedding band with brushed finish. Lightweight yet incredibly durable for everyday wear.',
    material: 'Grade 5 Titanium',
    sizes: ['7', '8', '9', '10', '11', '12', '13'],
    width: '6mm',
    features: [
      'Hypoallergenic',
      'Scratch resistant',
      'Lightweight',
      'Comfort fit interior',
    ],
  },
  {
    id: '6',
    name: 'Silver Cuff Bracelet',
    category: 'Bracelets',
    price: 259,
    images: [Img, Img],
    description:
      'Bold sterling silver cuff bracelet with hammered texture. Makes a strong style statement while remaining versatile.',
    material: 'Sterling Silver',
    length: 'Adjustable',
    width: '15mm',
    features: [
      'Solid sterling silver',
      'Hammered texture',
      'Adjustable opening',
      'Oxidized finish',
    ],
  },
  {
    id: '7',
    name: 'Gold Signet Ring',
    category: 'Rings',
    price: 599,
    images: [Img, Img],
    description:
      'Traditional signet ring in 10K gold with polished face. Perfect for engraving your personal insignia or initials.',
    material: '10K Gold',
    sizes: ['8', '9', '10', '11', '12'],
    width: '14mm',
    features: [
      '10K solid gold',
      'Engravable surface',
      'High polish finish',
      'Classic design',
    ],
  },
  {
    id: '8',
    name: 'Beaded Stone Bracelet',
    category: 'Bracelets',
    price: 129,
    images: [Img, Img],
    description:
      'Natural stone beaded bracelet featuring matte black onyx and lava stones. Earthy and masculine with a modern edge.',
    material: 'Natural Stones, Elastic Cord',
    length: '7.5 inches (stretches)',
    width: '8mm beads',
    features: [
      'Natural stones',
      'Stretch fit',
      'Aromatherapy compatible',
      'Handcrafted',
    ],
  },
  {
    id: '9',
    name: 'Silver Dog Tag Necklace',
    category: 'Chains',
    price: 199,
    images: [Img, Img],
    description:
      'Military-inspired dog tag necklace in sterling silver. Rugged style with a polished finish for contemporary appeal.',
    material: 'Sterling Silver',
    length: '24 inches',
    width: 'Tag: 50mm x 28mm',
    features: [
      'Engravable dog tag',
      'Ball chain included',
      'Oxidized details',
      'Military style',
    ],
  },
  {
    id: '10',
    name: 'Stainless Steel Cufflinks',
    category: 'Cufflinks',
    price: 149,
    images: [Img, Img],
    description:
      'Sophisticated stainless steel cufflinks with brushed finish. Essential accessories for the well-dressed gentleman.',
    material: 'Stainless Steel',
    dimensions: '18mm x 12mm',
    features: [
      'Brushed finish',
      'Bullet back closure',
      'Gift box included',
      'Tarnish resistant',
    ],
  },
  {
    id: '11',
    name: 'Black Leather Bracelet',
    category: 'Bracelets',
    price: 89,
    images: [Img, Img],
    description:
      'Minimalist black leather bracelet with stainless steel clasp. Simple, sleek, and effortlessly cool.',
    material: 'Genuine Leather, Stainless Steel',
    length: '8 inches',
    width: '10mm',
    features: [
      'Genuine leather',
      'Secure clasp',
      'Minimalist design',
      'Everyday wear',
    ],
  },
  {
    id: '12',
    name: 'Platinum Band Ring',
    category: 'Rings',
    price: 799,
    images: [Img, Img],
    description:
      'Luxurious platinum band with high polish finish. The ultimate in durability and prestige for a lifetime of wear.',
    material: '950 Platinum',
    sizes: ['8', '9', '10', '11', '12'],
    width: '5mm',
    features: [
      '950 platinum',
      'High polish',
      'Hypoallergenic',
      'Lifetime warranty',
    ],
  },
];
