import Head from "next/head";
import { Cormorant_Garamond, Inter } from "next/font/google";
import styles from "../styles/Home.module.scss";
import { ProductsPage } from "@entities/product/pages/products-page";


const cormorant = Cormorant_Garamond({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Products() {
  return (
    <>
      <Head>
        <title>Metalyze - Products</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${inter.variable} ${cormorant.variable}`}
      >
        <main className={styles.main}>
            <ProductsPage/>
        </main>
      </div>
    </>
  );
}
